### PR TITLE
added upsells

### PR DESCRIPTION
**Pull request by kabirvirji**
https://github.com/lemonstand/lemonstand-2/issues/3537

image

### CODE REVIEW

**Review by tomcornall — CHANGES_REQUESTED** [review]
@kabirvirji `product.related` is not actually used anymore (nor referenced in docs I don't believe).

It would make more sense to use `product.crossSells` here since it's the product page you're adding them to.

Upsells usually happen on cart/checkout pages, as a last minute purchase. So if you want to add upsells I'd do it on those pages.

**Comment by tomcornall** [comment]
I see that the original issue said to add upsells to the product page. Certainly it's possible, but just remember that upsells can only be added once the base-product is in the cart.

**Comment by kabirvirji** [comment]
image

**Comment by kabirvirji** [comment]
image

**Pull request merged**
